### ISSUE TITLE
yuh i know this is old but

### ISSUE THREAD

**Issue by Maxisthemoose** [clvrk/discord.js-member-count-channel#1]
https://github.com/clvrk/discord.js-member-count-channel/blob/ff904401e860f0708a479c74f9d8076ecb214a11/mc.js#L1

This'll rate limit you like friken hard core

**Comment by clvrk** [comment]
Lol, yep. I honestly don't know why I put all those events, couldn't be bothered to fix all that up though, *like I'd know how to in js anyway*.
